name: str()
image: str()
copy: list(include('copy_'), required=False)
run: list(str(), required=False)
limit: include('limit_', required=False)
expose: int(min=1024,max=49151, required=False)
env: map(str(), str(), required=False)
---
copy_:
    src: str()
    dest: str()

limit_:
  cpu: int(min=1,max=100,required=False)
  mem: int(min=1,max=2048,required=False)