name: my-container
image: ubuntu:18.04
copy:
- src: ./source1
  dest: /tmp/
- src: ./source2
  dest: /opt/
run:
  - sleep 10
  - echo "hello, world!"
limit:
  cpu: 10
  mem: 200
expose: 8080
env:
  PATH: /bin/
  USERNAME: johndoe
  PASSWORD: wordpass