name: my-container
image: ubuntu:18.04
actions:
  - copy:
      src: ./source1
      dest: /tmp/
  - run: sleep 10
  - run: echo "hello, world"
  - copy:
      src: ./source2
      dest: /tmp/source2
limit:
  cpu: 10
  mem: 200
expose: 8080